# All soldat DIRs here are aggregated into stats
soldat_dir:
  - /root/pyredis_stats/soldat

# These key-pairs are fed into redis.Redis() as **kwargs. See 
# https://redis-py.readthedocs.org/en/latest/ for available keys.
redis_connect:
  host: localhost

# Prefix for all keys. You can use this to keep track of different
# types of servers if you wish.
redis_prefix: 'piestats'

# Days to keep track of stats
data_retention: 30
